FROM alpine:latest
MAINTAINER Martin Simon <me@martinsimon.me>

RUN \
	apk add --update \
		nodejs \
		git && \
		npm -g install npm && \
		npm cache clean && \
		rm -rf /var/cache/apk/*

RUN \
	git clone https://github.com/MarvinMenzerath/HastebinPlus.git /opt/haste
	
RUN \
	mkdir -p $HOME

WORKDIR \
	/opt/haste

RUN \
	npm install
	
VOLUME /opt/haste/data

EXPOSE 8080

CMD ["npm", "start"]